version: '3'
services:
  mysqldb:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=CUSTOMERS
    ports:
      - "3306:3306"
    expose:
      - "3306"